export type ProductSort =
  | 'popularity'
  | 'price-asc'
  | 'price-desc'
  | 'newest'
  | 'rating';

export interface ProductItem {
  id: number;
  slug: string;
  name: string;
  category: string;
  colors: string[];
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  inStock: boolean;
  flashSale: boolean;
  cityIds: number[];
  countryIds: number[];
  badge: string;
  imageLabel: string;
}

export const productCategories = [
  'Manga',
  'Anime',
  'Collectibles',
  'Tech',
  'Snacks',
  'Maison',
] as const;

export const productColors = [
  { value: 'black', label: 'Noir', hex: '#111827' },
  { value: 'white', label: 'Blanc', hex: '#f8fafc' },
  { value: 'red', label: 'Rouge', hex: '#ef4444' },
  { value: 'blue', label: 'Bleu', hex: '#2563eb' },
  { value: 'gold', label: 'Or', hex: '#f59e0b' },
  { value: 'pink', label: 'Rose', hex: '#ec4899' },
] as const;

export const sortOptions: { value: ProductSort; label: string }[] = [
  { value: 'popularity', label: 'Popularite' },
  { value: 'price-asc', label: 'Prix croissant' },
  { value: 'price-desc', label: 'Prix decroissant' },
  { value: 'newest', label: 'Nouveautes' },
  { value: 'rating', label: 'Meilleure note' },
];

export const mockProducts: ProductItem[] = [
  {
    id: 1,
    slug: 'katana-display-stand',
    name: 'Katana Display Stand',
    category: 'Collectibles',
    colors: ['black', 'gold'],
    price: 39900,
    originalPrice: 45900,
    rating: 4.9,
    reviews: 124,
    inStock: true,
    flashSale: true,
    countryIds: [1, 3],
    cityIds: [101, 102, 301],
    badge: 'Top ventes',
    imageLabel: 'Stand samourai',
  },
  {
    id: 2,
    slug: 'notebook-studio-ghibli',
    name: 'Notebook Studio Ghibli',
    category: 'Manga',
    colors: ['white', 'blue'],
    price: 8500,
    rating: 4.8,
    reviews: 83,
    inStock: true,
    flashSale: false,
    countryIds: [1, 2, 3],
    cityIds: [101, 102, 201, 301],
    badge: 'Nouveau',
    imageLabel: 'Carnet Ghibli',
  },
  {
    id: 3,
    slug: 'headset-neon-tokyo',
    name: 'Headset Neon Tokyo',
    category: 'Tech',
    colors: ['black', 'blue'],
    price: 79,
    originalPrice: 99,
    rating: 4.7,
    reviews: 57,
    inStock: true,
    flashSale: true,
    countryIds: [2],
    cityIds: [201, 202],
    badge: 'Flash sale',
    imageLabel: 'Casque Tokyo',
  },
  {
    id: 4,
    slug: 'lucky-cat-tea-set',
    name: 'Lucky Cat Tea Set',
    category: 'Maison',
    colors: ['white', 'gold'],
    price: 27000,
    rating: 4.9,
    reviews: 61,
    inStock: true,
    flashSale: false,
    countryIds: [1, 3],
    cityIds: [101, 103, 301, 302],
    badge: 'Edition limitee',
    imageLabel: 'Tea set maneki-neko',
  },
  {
    id: 5,
    slug: 'demon-slayer-box',
    name: 'Demon Slayer Collector Box',
    category: 'Anime',
    colors: ['red', 'black'],
    price: 24900,
    originalPrice: 31900,
    rating: 4.8,
    reviews: 109,
    inStock: true,
    flashSale: true,
    countryIds: [1],
    cityIds: [101, 102, 104],
    badge: 'Promo forte',
    imageLabel: 'Collector box',
  },
  {
    id: 6,
    slug: 'tokyo-snack-pack',
    name: 'Tokyo Snack Pack',
    category: 'Snacks',
    colors: ['pink', 'white'],
    price: 18500,
    originalPrice: 22000,
    rating: 4.6,
    reviews: 41,
    inStock: true,
    flashSale: true,
    countryIds: [1, 3],
    cityIds: [101, 301],
    badge: 'Flash sale',
    imageLabel: 'Snack box',
  },
  {
    id: 7,
    slug: 'akira-poster-foil',
    name: 'Akira Poster Foil',
    category: 'Anime',
    colors: ['red', 'black'],
    price: 12900,
    rating: 4.5,
    reviews: 28,
    inStock: false,
    flashSale: false,
    countryIds: [1, 2],
    cityIds: [102, 201],
    badge: 'Rupture',
    imageLabel: 'Poster collector',
  },
  {
    id: 8,
    slug: 'ramen-bowl-premium',
    name: 'Ramen Bowl Premium',
    category: 'Maison',
    colors: ['blue', 'white'],
    price: 15900,
    rating: 4.7,
    reviews: 36,
    inStock: true,
    flashSale: false,
    countryIds: [1, 2, 3],
    cityIds: [101, 201, 301, 302],
    badge: 'Cuisine',
    imageLabel: 'Bol ramen',
  },
  {
    id: 9,
    slug: 'mecha-keycaps-set',
    name: 'Mecha Keycaps Set',
    category: 'Tech',
    colors: ['black', 'pink', 'white'],
    price: 34000,
    rating: 4.8,
    reviews: 72,
    inStock: true,
    flashSale: false,
    countryIds: [2, 3],
    cityIds: [201, 202, 302],
    badge: 'Setup desk',
    imageLabel: 'Keycaps neon',
  },
  {
    id: 10,
    slug: 'one-piece-figure-luffy',
    name: 'One Piece Figure Luffy',
    category: 'Collectibles',
    colors: ['red', 'blue'],
    price: 31500,
    rating: 4.9,
    reviews: 89,
    inStock: true,
    flashSale: false,
    countryIds: [1, 2, 3],
    cityIds: [101, 102, 201, 301],
    badge: 'Best seller',
    imageLabel: 'Figure Luffy',
  },
  {
    id: 11,
    slug: 'manga-starter-bundle',
    name: 'Manga Starter Bundle',
    category: 'Manga',
    colors: ['black', 'white'],
    price: 22500,
    rating: 4.6,
    reviews: 54,
    inStock: true,
    flashSale: false,
    countryIds: [1],
    cityIds: [101, 103, 104],
    badge: 'Bundle',
    imageLabel: 'Pack mangas',
  },
  {
    id: 12,
    slug: 'sailor-moon-pouch',
    name: 'Sailor Moon Travel Pouch',
    category: 'Anime',
    colors: ['pink', 'blue'],
    price: 9900,
    rating: 4.7,
    reviews: 44,
    inStock: true,
    flashSale: false,
    countryIds: [1, 3],
    cityIds: [102, 301, 302],
    badge: 'Cute pick',
    imageLabel: 'Travel pouch',
  },
];
